name: spharm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - alsa-lib=1.2.15.3
  - assimp=5.4.3
  - astropy=6.1.7
  - astropy-iers-data=0.2026.1.12.0.42.13
  - asttokens=3.0.1
  - async-timeout=5.0.1
  - attr=2.5.2
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - blinker=1.9.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - cli11=2.6.0
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dash=3.3.0
  - dbus=1.16.2
  - decorator=5.2.1
  - double-conversion=3.4.0
  - ducc0=0.40.0
  - embree=4.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fftw=3.3.10
  - flask=3.1.2
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - frozenlist=1.7.0
  - gl2ps=1.4.2
  - glew=2.2.0
  - glfw=3.4
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - igl=2.6.1
  - importlib-metadata=8.7.0
  - ipython=8.37.0
  - ipywidgets=8.1.8
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jsoncpp=1.9.6
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcups=2.3.3
  - libcurl=8.18.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm20=20.1.8
  - libllvm21=21.1.8
  - liblzf=3.6
  - liblzma=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.1.1
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvmlite=0.46.0
  - loguru=0.7.3
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mesalib=25.0.5
  - msgpack-python=1.1.2
  - multidict=6.7.0
  - munkres=1.1.4
  - narwhals=2.15.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - numba=0.63.1
  - numpy=1.26.4
  - open3d=0.19.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - plotly=6.5.1
  - pooch=1.8.2
  - proj=9.7.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pyerfa=2.0.1.5
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.3.1
  - pyshtools=4.13.1
  - pyside6=6.10.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyvista=0.46.4
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt6-main=6.10.1
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - retrying=1.4.2
  - rpds-py=0.30.0
  - scikit-learn=1.7.2
  - scipy=1.12.0
  - scooby=0.11.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - sqlite=3.51.2
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tinyobjloader=1.0.7
  - tk=8.6.13
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trimesh=4.11.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - umap-learn=0.5.11
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - utfcpp=4.09
  - viskores=1.0.0
  - vtk-base=9.5.2
  - wayland=1.24.0
  - wcwidth=0.2.14
  - werkzeug=3.1.5
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wslink=2.5.0
  - xarray=2025.6.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
